### ISSUE TITLE
[RFC] don't pass `out_dir` to writers

### ISSUE THREAD

**Issue by emcastillo** [pfnet/pytorch-pfn-extras#475]
After an offline discussion with @belltailjp,
he proposes that the path to save objects through the writers should be stored in the filesystem object instead of passing an`out_dir` string directly to the writers.

I agree with this proposal

**Comment by kmaehashi** [comment]
I think changing the default value of `out_dir` from `None` to `''` is better here, so that underlying filesystem objects can be reused between multiple writer instances. e.g., create a FileSystem pointing to the root of an S3 bucket, and create two PPE writers for snapshot and logs, both under the same bucket.
